language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '7'
before_script:
  - npm install -g bower firebase-tools
script:
  # - polymer test
  - sh go
